# Need to make all of these user options in Yeoman

# Site settings
title: <%= projectName %>
email: <%= authorEmail %>
description: <%= projectDescription %>
url: <%= projectURL %>
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: <%= authorTwitter %>
github_username:  <%= authorGithub %>

# Build settings
markdown: kramdown
